import { AiFillStar } from "react-icons/ai";

import React from "react";
const Data = [
  
  {
    id:1,
    img: 'a7la2sater.jpg',
    title: "The best Legends",
    rate:"4",
    star: <AiFillStar className="rating-star" />,
    reviews: "(54 reviews)",
    prevPrice: "$240,00",
    newPrice: "200",
    publisher: "Nahdet Misr",
    category: "Adventure",
    quantity:"1",
  },
  {
    id:2,
    img: "cukur.jpg",
    title: "CUKUR",
    star: <AiFillStar className="rating-star" />,
    rate:"4.5",
    reviews: "(250 reviews)",
    prevPrice: "$240,00",
    newPrice: "200",
    publisher: "Al-Diwan",
    category: "Action",
    quantity:"1",
  },
  {
    id:3,
    img: "HarryPotter1.jpg",
    title: "Harry Potter",
    star: <AiFillStar className="rating-star" />,
    rate:"4",
    reviews: "(250 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    publisher: "Nahdet Misr",
    category: "Fiction",
    quantity:"1",
  },

  {
    id:4,
    img: "HarryPotter2.jpg",
    title: "Harry Potter",
    star: <AiFillStar className="rating-star" />,
    rate:"3.5",
    reviews: "(64 reviews)",
    prevPrice: "$220,00",
    newPrice: "200",
    publisher: "Nahdet Misr",
    category: "Fantasy",
    quantity:"1",
  },
  {
    id:5,
    img: "HarryPotter3.jpg",
    title: "Harry Potter",
    star: <AiFillStar className="rating-star" />,
    rate:"4",
    reviews: "(150 reviews)",
    prevPrice: "$340,00",
    newPrice: "200",
    publisher: "Nahdet Misr",
    category: "Fiction",
    quantity:"1",
  },
  {
    id:6,
    img: "HarryPotter4.jpg",
    title: "Harry Potter",
    star: <AiFillStar className="rating-star" />,
    rate:"5",
    reviews: "(19 reviews)",
    prevPrice: "$160,00",
    newPrice: "150",
    publisher: "Nahdet Misr",
    category: "Fantasy",
    quantity:"1",
  },
  {
    id:7,
    img: "crime.jpg",
    title: "Crime in Fog",
    star: <AiFillStar className="rating-star" />,
    rate:"2",
    reviews: "(27 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    publisher: "Dar Al-Masriya",
    category: "Horror",
    quantity:"1",
  },
  {id:8,
    img: "dalida.jpg",
    title: "Dalida",
    star: <AiFillStar className="rating-star" />,
    rate:"3.5",
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    publisher: "Al-Shrouk",  
    category: "Biography",
    quantity:"1",
  },
  {id:9,
    img: "ekadoly.jpg",
    title: "Ekadoli",
    star: <AiFillStar className="rating-star" />,
    rate:"4.5",
    reviews: "(180 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    publisher: "Nahdet Misr",
    category: "Fiction",
    quantity:"1",
  },
  {
    id:10,
    img: "femaleinheart.jpg",
    title: "A woman in my heart",
    star: <AiFillStar className="rating-star" />,
    rate:"4.5",
    reviews: "(200 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    publisher: "Al-Diwan",
    category: "Narrative",
    quantity:"1",
  },

  {id:11,
    img: "friendsera.jpg",
    title: "Friends",
    star: <AiFillStar className="rating-star" />,
    rate:"3",
    reviews: "(13 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    publisher: "Nahdet Misr",
    category: "Action",
    quantity:"1",
  },

  {
    id:12,
    img: "gartenlaws.jpg",
    title: "Garten Laws",
    star: <AiFillStar className="rating-star" />,
    rate:"3.5",
    reviews: "(45 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    publisher: "Al-Shrouk",
    category: "Historical",
    quantity:"1",
  },

 
  {id:13,
    img: "hictor.jpg",
    title: "Hictor",
    star: <AiFillStar className="rating-star" />,
    rate:"4",
    reviews: "(214 reviews)",
    prevPrice: "$215,00",
    newPrice: "150",
    publisher: "Al-Diwan",
    category: "Action",
    quantity:"1",
  },
  {
    id:14,
    img: "hourofbaghdad.jpg",
    title: "Hours of Baghdad",
    star: <AiFillStar className="rating-star" />,
    rate:"4.5",
    reviews: "(163 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    publisher: "Al-Diwan",
    category: "Historical",
    quantity:"1",
  },
  {
    id:15,
    img: "hipta.jpg",
    title: "Hipta",
    star: <AiFillStar className="rating-star" />,
    rate:"5",
    reviews: "(163 reviews)",
    prevPrice: "$100,00",
    newPrice: "50",
    publisher: "Al-Diwan",
    category: "Narrative",
    quantity:"1",
  },
  {
    id:16,
    img: "sak2lbambo.jpg",
    title: "ساق البامبو",
    star: <AiFillStar className="rating-star" />,
    rate:"3.5",
    reviews: "(163 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    publisher: "Al-Shrouk",
    category: "Historical",
    quantity:"1",
  },
  {id:17,
    img: "tripleofgranada.jpg",
    title: "ثلاثية غرناطة",
    star: <AiFillStar className="rating-star" />,
    rate:"4",
    reviews: "(163 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    publisher: "Dar Al-Masriya",
    category: "Historical",
    quantity:"1",
  },
  { id:18,
    img: "yotopia.jpg",
    title: "يوتوبيا",
    star: <AiFillStar className="rating-star" />,
    rate:"4",
    reviews: "(163 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    publisher: "Al-Diwan",
    category: "Adventure",
    quantity:"1",
  },
  {id:19,
    img: "dandoreh.jpg",
    title: "الطنطورية",
    star: <AiFillStar className="rating-star" />,
    rate:"4",
    reviews: "(163 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    publisher: "Nahdet Misr",
    category: "Historical",
    quantity:"1",
  },
  {id:20,
    img: "anti5arastos.jpg",
    title: "انتخريستوس",
    star: <AiFillStar className="rating-star" />,
    rate:"4",
    reviews: "(163 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    publisher: "Al-Diwan",
    category: "Horror",
    quantity:"1",
  },
 

 
];

export default Data;