import { AiFillStar } from "react-icons/ai";

const data = [
  
  {
    img: "./images/a7la2sater.jpg",
    title: "The best Legends",
    star: <AiFillStar className="rating-star" />,
    reviews: "(54 reviews)",
    prevPrice: "$240,00",
    newPrice: "200",
    publisher: "Nahdet Misr",
    category: "Adventure",
  },
  {
    img: "./images/cukur.jpg",
    title: "CUKUR",
    star: <AiFillStar className="rating-star" />,
    reviews: "(250 reviews)",
    prevPrice: "$240,00",
    newPrice: "200",
    publisher: "Al-Diwan",
    category: "Action",
  },
  {
    img: "./images/HarryPotter1.jpg",
    title: "Harry Potter",
    star: <AiFillStar className="rating-star" />,
    reviews: "(250 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    publisher: "Nahdet Misr",
    category: "Fiction",
  },

  {
    img: "./images/HarryPotter2.jpg",
    title: "Harry Potter",
    star: <AiFillStar className="rating-star" />,
    reviews: "(64 reviews)",
    prevPrice: "$220,00",
    newPrice: "200",
    publisher: "Nahdet Misr",
    category: "Fantasy",
  },
  {
    img: "./images/HarryPotter3.jpg",
    title: "Harry Potter",
    star: <AiFillStar className="rating-star" />,
    reviews: "(150 reviews)",
    prevPrice: "$340,00",
    newPrice: "200",
    publisher: "Nahdet Misr",
    category: "Fiction",
  },
  {
    img: "./images/HarryPotter4.jpg",
    title: "Harry Potter",
    star: <AiFillStar className="rating-star" />,
    reviews: "(19 reviews)",
    prevPrice: "$160,00",
    newPrice: "150",
    publisher: "Nahdet Misr",
    category: "Fantasy",
  },
  {
    img: "./images/crime.jpg",
    title: "Crime in Fog",
    star: <AiFillStar className="rating-star" />,
    reviews: "(27 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    publisher: "Dar Al-Masriya",
    category: "Horror",
  },
  {
    img: "./images/dalida.jpg",
    title: "Dalida",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    publisher: "Al-Shrouk",  
    category: "Biography",
  },
  {
    img: "./images/ekadoly.jpg",
    title: "Ekadoli",
    star: <AiFillStar className="rating-star" />,
    reviews: "(180 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    publisher: "Nahdet Misr",
    category: "Fiction",
  },
  {
    img: "./images/femaleinheart.jpg",
    title: "A woman in my heart",
    star: <AiFillStar className="rating-star" />,
    reviews: "(200 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    publisher: "Al-Diwan",
    category: "Narrative",
  },

  {
    img: "./images/friendsera.jpg",
    title: "Friends",
    star: <AiFillStar className="rating-star" />,
    reviews: "(13 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    publisher: "Nahdet Misr",
    category: "Action",
  },

  {
    img: "./images/gartenlaws.jpg",
    title: "Garten Laws",
    star: <AiFillStar className="rating-star" />,
    reviews: "(45 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    publisher: "Al-Shrouk",
    category: "Historical",
  },

 
  {
    img: "./images/hictor.jpg",
    title: "Hictor",
    star: <AiFillStar className="rating-star" />,
    reviews: "(214 reviews)",
    prevPrice: "$215,00",
    newPrice: "150",
    publisher: "Al-Diwan",
    category: "Action",
  },
  {
    img: "./images/hourofbaghdad.jpg",
    title: "Hours of Baghdad",
    star: <AiFillStar className="rating-star" />,
    reviews: "(163 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    publisher: "Al-Diwan",
    category: "Historical",
  },
  {
    img: "./images/hipta.jpg",
    title: "Hipta",
    star: <AiFillStar className="rating-star" />,
    reviews: "(163 reviews)",
    prevPrice: "$100,00",
    newPrice: "50",
    publisher: "Al-Diwan",
    category: "Narrative",
  },
  {
    img: "./images/sak2lbambo.jpg",
    title: "ساق البامبو",
    star: <AiFillStar className="rating-star" />,
    reviews: "(163 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    publisher: "Al-Shrouk",
    category: "Historical",
  },
  {
    img: "./images/tripleofgranada.jpg",
    title: "ثلاثية غرناطة",
    star: <AiFillStar className="rating-star" />,
    reviews: "(163 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    publisher: "Dar Al-Masriya",
    category: "Historical",
  },
  {
    img: "./images/yotopia.jpg",
    title: "يوتوبيا",
    star: <AiFillStar className="rating-star" />,
    reviews: "(163 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    publisher: "Al-Diwan",
    category: "Adventure",
  },
  {
    img: "./images/dandoreh.jpg",
    title: "الطنطورية",
    star: <AiFillStar className="rating-star" />,
    reviews: "(163 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    publisher: "Nahdet Misr",
    category: "Historical",
  },
  {
    img: "./images/anti5arastos.jpg",
    title: "انتخريستوس",
    star: <AiFillStar className="rating-star" />,
    reviews: "(163 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    publisher: "Al-Diwan",
    category: "Horror",
  },
 

 
];

export default data;